"""Init database model job_groups, timesheets, work_record

Revision ID: f17016370005
Revises: 
Create Date: 2021-11-28 01:55:21.917457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f17016370005"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_groups",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("hourly_pay", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_index(op.f("ix_job_groups_name"), "job_groups", ["name"], unique=False)
    op.create_table(
        "timesheets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path"),
    )
    op.create_index(op.f("ix_timesheets_id"), "timesheets", ["id"], unique=False)
    op.create_table(
        "work_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("job_group_name", sa.String(), nullable=False),
        sa.Column("work_hour", sa.Float(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_group_name"],
            ["job_groups.name"],
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["timesheets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_work_records_id"), "work_records", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_work_records_id"), table_name="work_records")
    op.drop_table("work_records")
    op.drop_index(op.f("ix_timesheets_id"), table_name="timesheets")
    op.drop_table("timesheets")
    op.drop_index(op.f("ix_job_groups_name"), table_name="job_groups")
    op.drop_table("job_groups")
    # ### end Alembic commands ###
